### ISSUE TITLE
Uebung02 fehlt

### ISSUE THREAD

**Issue by martinchristen** [StefanK2000/UebungenHS2022#1]
Die Uebung02 fehlt leider.

**Comment by StefanK2000** [comment]
Ich habe leider vergessen, die Aufgaben zu pushen:

***@***.***

Von: Martin Christen ***@***.***>
Gesendet: Donnerstag, 6. Oktober 2022 12:19
An: StefanK2000/UebungenHS2022 ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [StefanK2000/UebungenHS2022] Uebung02 fehlt (Issue #1)


Die Uebung02 fehlt leider.

-
